### PR TITLE
Bugfix/is int missing is numeric filter

### PR DESCRIPTION
**Pull request by apbiprogr**
Version 0.6.1
Inspekt.php
isInt() function
We expect that isInt() would return false when the empty string is passed in, but because isInt() is missing the is_numeric() test, it returns true.
Here's the comment that makes it look like is_numeric() was intended, but maybe forgotten:
802         /**
803          * we exit here if not is_numeric, because str_replace below will cast bools
804          * to numerics
805          */
Line 806 is missing the is_numeric() check. Here's what it might look like:
806         if (is_object($value) || is_bool($value) || !is_numeric($value)) {
The tests/InspektTest.php file has no tests that test for non-numbers.
A test for the empty string and a few other non-integer strings would be appropriate.
Thanks for considering this.

### CODE REVIEW

**Comment by benedmunds** [comment]
Thanks!

**Comment by benedmunds** [comment]
Can you do fix the README conflicts as well? Happy to merge after that.

**Comment by apbiprogr** [comment]
Yeah, I don't really understand where the readme problem came from.
I cloned 0.6.1, changed Inspekt.php and InspektTest.php, and that readme file showed up with changes.
Can you help me understand that, please?
________________________________

**Comment by benedmunds** [comment]
No worries, I merged it in and cut version 0.6.2.  Thanks again!

**Comment by apbiprogr** [comment]
Oh, I see. This becomes the next version and needs a changelog entry.
Thanks for your quick response.
This change will be very helpful to us.
We were going to have a very clunky work around.
Then someone suggested submitting a PR.
This is my first contribution to an opensource project.
I'm very pleased with the process.
Good-bye,
-Andy
________________________________

**Comment by benedmunds** [comment]
Oh that’s awesome to hear, welcome to open source!  Thanks for the contribution!

-Ben Edmunds

**Pull request merged**
